### ISSUE TITLE
Error when adding breakpoint

### ISSUE THREAD

**Issue by chess-equality** [sourceplusplus/sourceplusplus#1055]
When adding breakpoint:

![error-1_add-breakpoint](https://github.com/sourceplusplus/sourceplusplus/assets/29477940/f9d115fc-13d9-415f-bdcb-30d44c5ed51f)

**Comment by BFergerson** [comment]
You should just press the "Report and Clear All" button. It'll make an issue for you with all the necessary details.

**Comment by BFergerson** [comment]
Please create separate issues for problems you find.
