### ISSUE TITLE
In dark mode / theme, labels are not showing

### ISSUE THREAD

**Issue by chess-equality** [sourceplusplus/sourceplusplus#1056]
![add_brkpt_dark-mode-no-labels](https://github.com/sourceplusplus/sourceplusplus/assets/29477940/696fb3ec-4246-408a-b9a1-8ead10d7c606)

**Comment by chess-equality** [comment]
In progress.

**Comment by chess-equality** [comment]
Potential lead:

https://youtrack.jetbrains.com/issue/SCL-20713

**Comment by chess-equality** [comment]
First tests:

![image](https://github.com/sourceplusplus/sourceplusplus/assets/29477940/dcf85981-5d6d-4d2f-b8aa-08bc6a6cf4c3)

**Comment by chess-equality** [comment]
![image](https://github.com/sourceplusplus/sourceplusplus/assets/29477940/f66d016e-41aa-4041-b369-4a703f701b6e)

**Comment by BFergerson** [comment]
> First tests:
> 
> ![image](https://user-images.githubusercontent.com/29477940/249028491-dcf85981-5d6d-4d2f-b8aa-08bc6a6cf4c3.png)

Looks really nice!

**Comment by chess-equality** [comment]
Already finished converting all the Swing components to their JB* counterparts (https://git.jetbrains.org/?p=idea/community.git;a=tree;f=platform/platform-api/src/com/intellij/ui/components) and I'm currently testing each screen.
