### ISSUE TITLE
View Activity missing

### ISSUE THREAD

**Issue by chess-equality** [sourceplusplus/sourceplusplus#1058]
![view_activity_missing](https://github.com/sourceplusplus/sourceplusplus/assets/29477940/d0e12736-7f3f-4c3b-8a80-e2c05ab95aad)

**Comment by BFergerson** [comment]
The demo-app application was down. The yellow cloud with a slash through it shows why "View Activity" wasn't available. That should probably be more prominent but either way, it was unable to find the endpoint. When you go to Live Activity -> Endpoints, you should see something like this:
 
![image](https://github.com/sourceplusplus/sourceplusplus/assets/3278877/055bcaac-9249-41ac-abdd-982983bd1a29)

I've rebooted the spp-demo application. Please give it another try.
