### ISSUE TITLE
More control over live variable depth/size

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/sourceplusplus#428]
Sometimes when debugging with a breakpoint, one may find what is causing an issue, but be unable view a certain desired variable due to max depth or max size restrictions. Allowing the developer to choose a certain variable, or field on that variable (or something deeper in the variable tree) in the IDE, and have the breakpoint include data on that variable further than the maximum depth (maybe allow the developer to input the depth). This allows for superficial variable information by default (as it is now), but more detailed information when debugging a specific bug.

**Comment by BFergerson** [comment]
Nice feature request. I think a good solution would be to add two more permissions to the platform: `LIVE_INSTRUMENT_DEPTH` & `LIVE_INSTRUMENT_MAX_DEPTH`. Developers would then be given the ability to configure what depth they prefer under the max depth. For convenience, there should be a way to save the default max depth per object type.

**Comment by BFergerson** [comment]
Also, max depth/size should be configurable by the variable name. That is, a user should be able to create a live breakpoint that collects multiple variables but allows for a specific variable (e.g. `deepMap`) to have max depth disabled or with a specific depth.

**Comment by BFergerson** [comment]
Finished work on probe-jvm for this. Still need to implement permission/graphql on platform.
