### ISSUE TITLE
Impl JavaScript IDE support

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/sourceplusplus#522]
JavaScript support is an IU feature, not included in IC, so the node marker would have to depend on IntelliJ ultimate. The jetbrains plugin already depends on community edition, so it cannot include javascript in the plugin dependencies.

**Comment by BFergerson** [comment]
Basic support for live breakpoints and logs has been added. Will add more instruments as SkyWalking improves support for JavaScript.

Thanks for the initiative.
