### ISSUE TITLE
LiveInstrument Storage

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/sourceplusplus#616]
Live instruments are currently stored in memory. When the platform goes down everything saved about live instruments is erased. This ticket is to extend the functionality of `CoreStorage` to include the ability to create, update, and remove live instruments.

The following API should be implemented:
```kotlin
/**
 * Add a new [LiveInstrument] to the platform.
 */
suspend fun addLiveInstrument(instrument: LiveInstrument): LiveInstrument

/**
 * Update an existing [LiveInstrument] on the platform with the given id.
 */
suspend fun updateLiveInstrument(id: String, instrument: LiveInstrument): LiveInstrument

/**
 * Remove the [LiveInstrument] with the given id.
 */
suspend fun removeLiveInstrument(id: String): Boolean

/**
 * Get the [LiveInstrument] with the given id.
 */
suspend fun getLiveInstrument(id: String): LiveInstrument?

/**
 * Retrieve all [LiveInstrument]s where [LiveInstrument.pending] is true.
 */
suspend fun getPendingLiveInstruments(): List<LiveInstrument>
```

The following tasks should be done:

- [ ] Implement the API given above for both RedisStorage and MemoryStorage
- [ ] Add tests to BaseStorageITTest to validate the API given above

---

Prerequisite of #457

**Comment by abdlquadri** [comment]
@BFergerson Got this.
