### ISSUE TITLE
Fields that are not exported by their module cause the parent object to fail

### ISSUE THREAD

**Issue by MrMineO5** [sourceplusplus/sourceplusplus#678]
When the JVM probe generates debug information for objects, it reads their fields. If one of those fields is not exported, the entire object is marked with EXCEPTION_OCCURRED rather than just that field.
`Unable to make field sun.net.httpserver.ExchangeImpl sun.net.httpserver.HttpExchangeImpl.impl accessible: module jdk.httpserver does not "opens sun.net.httpserver" to unnamed module @2da3b078`

**Comment by BFergerson** [comment]
prerequisite: #552

**Comment by MrMineO5** [comment]
Related to: google/gson#1979

**Comment by BFergerson** [comment]
Spend a bit of time trying to figure this issue out. I have a basic working example that needs to be cleaned up. Taking a break from this issue and will look to have it done for the next version.
